plugins {
    id 'com.android.application'
    id 'com.google.devtools.ksp'
    id 'kotlin-android'
}

android {
    namespace 'com.shortendesign.k9keyboard'
    compileSdkVersion 36

    defaultConfig {
        applicationId "com.shortendesign.k9keyboard"
        minSdk 19
        targetSdkVersion 36
        versionCode 3
        versionName "0.12.1"

        vectorDrawables.generatedDensities = ['mdpi', 'hdpi']

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
    namespace 'com.shortendesign.k9keyboard'
}

dependencies {
    implementation 'androidx.test.ext:junit-ktx:1.2.1'
    def roomVersion = "2.6.1"

    implementation 'androidx.core:core-ktx:1.13.1'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation("androidx.room:room-common:$roomVersion")
    implementation("androidx.room:room-runtime:$roomVersion")
    implementation("androidx.room:room-ktx:$roomVersion")
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.5.2'
    annotationProcessor("androidx.room:room-compiler:$roomVersion")
    ksp "androidx.room:room-compiler:$roomVersion"
    testImplementation 'org.robolectric:robolectric:4.6'
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.4.2"
    testImplementation 'junit:junit:4.12'
}